basePath: /
definitions:
  model.Auth:
    properties:
      authCode:
        description: 鉴权识别码
        type: string
      authName:
        description: 鉴权名称
        type: string
      authType:
        description: 鉴权类型
        type: string
      createdAt:
        description: 创建时间
        type: string
      expireTime:
        description: 过期时间
        type: string
      id:
        description: ID
        type: string
      isEnabled:
        description: 是否启用
        type: boolean
      updatedAt:
        description: 更新时间
        type: string
      user:
        $ref: '#/definitions/model.User'
        description: 用户
        type: object
      userId:
        description: 用户ID
        type: string
      verifyTime:
        description: 认证时间
        type: string
    type: object
  model.AuthAccountLoginReq:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  model.AuthAccountLoginRes:
    properties:
      accessToken:
        type: string
      expiresIn:
        description: 过期时间（分钟）
        type: integer
      message:
        type: string
      tokenType:
        type: string
    required:
    - accessToken
    - expiresIn
    - message
    - tokenType
    type: object
  model.Group:
    properties:
      createdAt:
        description: 创建时间
        type: string
      id:
        description: ID
        type: string
      leader:
        $ref: '#/definitions/model.User'
        description: 队长
        type: object
      leaderId:
        description: 队长ID
        type: string
      name:
        description: 组名称
        type: string
      updatedAt:
        description: 更新时间
        type: string
      users:
        description: 队员
        items:
          $ref: '#/definitions/model.User'
        type: array
    type: object
  model.Menu:
    properties:
      children:
        description: 子菜单
        items:
          $ref: '#/definitions/model.Menu'
        type: array
      createdAt:
        description: 创建时间
        type: string
      icon:
        description: 菜单图标
        type: string
      id:
        description: ID
        type: string
      name:
        description: 菜单名称
        type: string
      parent:
        $ref: '#/definitions/model.Menu'
        description: 父菜单
        type: object
      parentId:
        description: 父ID
        type: string
      path:
        description: 菜单路径
        type: string
      roles:
        description: 角色
        items:
          $ref: '#/definitions/model.Role'
        type: array
      sort:
        description: 排序
        type: integer
      updatedAt:
        description: 更新时间
        type: string
    type: object
  model.PaginReq:
    properties:
      page:
        type: integer
      size:
        type: integer
      sort:
        type: string
    type: object
  model.Role:
    properties:
      createdAt:
        description: 创建时间
        type: string
      id:
        description: ID
        type: string
      menus:
        description: 菜单
        items:
          $ref: '#/definitions/model.Menu'
        type: array
      name:
        description: 角色名称
        type: string
      updatedAt:
        description: 更新时间
        type: string
      users:
        description: 用户
        items:
          $ref: '#/definitions/model.User'
        type: array
    type: object
  model.User:
    properties:
      address:
        description: 地址
        type: string
      auths:
        description: 帐号
        items:
          $ref: '#/definitions/model.Auth'
        type: array
      avatar:
        description: 昵称
        type: string
      birthday:
        description: 生日
        type: string
      bloodType:
        description: 血型(ABO)
        type: string
      createdAt:
        description: 创建时间
        type: string
      email:
        description: 邮箱
        type: string
      friends:
        description: 友
        items:
          $ref: '#/definitions/model.User'
        type: array
      gender:
        description: 性别
        type: integer
      groups:
        description: 组
        items:
          $ref: '#/definitions/model.Group'
        type: array
      height:
        description: 身高(cm)
        type: number
      homepage:
        description: 个人主页
        type: string
      id:
        description: ID
        type: string
      intro:
        description: 简介
        type: string
      lives:
        description: 生活轨迹
        type: string
      luckyNumbers:
        description: 幸运数字
        type: string
      mobile:
        description: 手机
        type: string
      name:
        description: 姓名
        type: string
      nickname:
        description: 昵称
        type: string
      notice:
        description: 备注
        type: string
      roles:
        description: 角色
        items:
          $ref: '#/definitions/model.Role'
        type: array
      score:
        description: 积分
        type: integer
      tags:
        description: 标签
        type: string
      updatedAt:
        description: 更新时间
        type: string
      userNo:
        description: 编号
        type: integer
    type: object
  model.UserListRes:
    properties:
      page:
        type: integer
      rows:
        items:
          $ref: '#/definitions/model.User'
        type: array
      size:
        type: integer
      total:
        type: integer
    required:
    - page
    - rows
    - size
    - total
    type: object
host: localhost:4000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /admin/login/account:
    post:
      consumes:
      - application/json
      description: 帐号登录...
      parameters:
      - description: 登录
        in: body
        name: 参数
        required: true
        schema:
          $ref: '#/definitions/model.AuthAccountLoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.AuthAccountLoginRes'
      summary: 帐号登录
      tags:
      - admin
  /admin/users:
    get:
      consumes:
      - application/json
      description: 用户列表...
      parameters:
      - in: query
        name: page
        type: integer
      - in: query
        name: size
        type: integer
      - in: query
        name: sort
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.UserListRes'
      security:
      - ApiKeyAuth: []
      summary: 用户列表
      tags:
      - user
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
x-extension-openapi:
  example: value on a json format
